#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Horidoro AV — build script.

Stitches the modules in horidoro/ into ONE distributable file
(horidoro-av.py) that people run with:  python3 horidoro-av.py

How it works: each module's source is embedded and loaded at startup into
sys.modules via a tiny loader, so cross-module imports (from state import
State, import actions, ...) keep working exactly as they do in development.

Usage:  python3 build.py
"""

from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "horidoro"
OUT = ROOT / "horidoro-av.py"

# Order matters: a module's imports must already be loaded when it runs.
# watcher.py is imported by actions.py, so it loads before installer/actions.
MODULES = ["branding", "state", "shell", "watcher", "templates",
           "installer", "updater", "actions", "gui"]

LOADER = '''\
# --- internal module loader: keeps cross-module imports working in one file ---
import sys as _sys
import types as _types

def _load_module(name, source):
    mod = _types.ModuleType(name)
    mod.__file__ = __file__
    exec(compile(source, "<horidoro-av:" + name + ">", "exec"), mod.__dict__)
    _sys.modules[name] = mod
    return mod
'''

HEADER = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Horidoro AV — Local-first Antivirus for Linux
by Commander Sabi  |  engine: ClamAV (GPLv2)

Single-file build generated by build.py from the horidoro/ source modules.
Do not edit this file directly — edit the modules and rebuild.

MIT License — Copyright (c) 2026 Commander Sabi (Horidoro AV)
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Run:  python3 horidoro-av.py
"""

'''


def main():
    parts = [HEADER, LOADER]
    for i, name in enumerate(MODULES):
        src = (SRC / f"{name}.py").read_text()
        banner = f"\n# ======================================================================\n" \
                 f"# SECTION {i+1}: {name}\n" \
                 f"# ======================================================================\n"
        parts.append(banner + f"_load_module({name!r}, {src!r})\n")
    parts.append('\nfrom gui import main\n\n'
                'if __name__ == "__main__":\n    main()\n')
    OUT.write_text("".join(parts))
    print(f"Built {OUT} ({OUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
